services:
  db:
    image: postgres:latest
    container_name: tower_tapper_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tower_tapper
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: tower_tapper_server
    env_file:
      - ./server/.env
    environment:
      - BOT_TOKEN=7730016619:AAH27CVP92RPW4qw8mmdEfFyApqzgLVtAz0
      - DB_HOST=db
      - DB_NAME=tower_tapper
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - TEST_MODE=false
      - GAME_URL=bd91-142-93-192-115.ngrok-free.app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: tower_tapper_client
    ports:
      - "80:80"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - server

volumes:
  postgres_data: 