services:
  db:
    image: postgres:latest
    container_name: tower_tapper_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tower_tapper_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: tower_tapper_server
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SERVER_PORT=${SERVER_PORT}
      - TEST_MODE=${TEST_MODE}
      - CLIENT_URL=${CLIENT_URL}
      - SERVER_URL=${SERVER_URL}
      - BOT_TOKEN=${BOT_TOKEN}
    expose:
      - "8080"
    networks:
      - tower_tapper_net
    depends_on:
      db:
        condition: service_healthy

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: tower_tapper_client
    expose:
      - "80"
    volumes:
      - ./client:/app
    networks:
      - tower_tapper_net
    depends_on:
      - server

networks:
  tower_tapper_net:
    driver: bridge

volumes:
  postgres_data: 