   run:
     timeout: 5m
   issues:
     exclude-rules:
       - path: _test\.go
         linters:
           - errcheck
   linters:
     enable:
       - errcheck
       - gosimple
       - govet
       - staticcheck
       - unused